Added test for empty scopes
Ethan-Arrowood/fastify-jwt-authz pull request #5
Opened 2018-01-21 15:36 UTC by benceHornyak

Please give me a review about the test.. Are there any bad-practice that I used? Any way to improve the test?

Thanks

part of #2

2018-01-21 23:31 UTC, Ethan-Arrowood commented
This looks good so far! Keep it up 😄

2018-01-23 17:50 UTC, benceHornyak commented
I had to make some changes regarding the scope checking to be 100%.. included a happy path as well.. 
Without it line 122 wouldn't throw the error

2018-01-23 17:54 UTC, Ethan-Arrowood commented
Incredible! Great job. Let me do a quick code review and lets see if we can get this merged.

2018-01-23 18:01 UTC, Ethan-Arrowood requested changes
Okay just change the name of the happy path test and its good to merge 😄

2018-01-23 18:01 UTC, Ethan-Arrowood commented on test.js
> +test('Happy path', function (t) {
lets rename this test to 'should verify user scope'

2018-01-23 18:03 UTC, Ethan-Arrowood approved these changes
LGTM 🎉

2018-01-23 18:04 UTC, Ethan-Arrowood commented
Great work! Once Travis-CI passes i'll merge this. Thank you for contributing 👍

2018-01-23 18:05 UTC, merged